//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_ContentSizeFitter_FitModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.ContentSizeFitter.FitMode));
		L.RegVar("Unconstrained", get_Unconstrained, null);
		L.RegVar("MinSize", get_MinSize, null);
		L.RegVar("PreferredSize", get_PreferredSize, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Unconstrained(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.ContentSizeFitter.FitMode.Unconstrained);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MinSize(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.ContentSizeFitter.FitMode.MinSize);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PreferredSize(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.ContentSizeFitter.FitMode.PreferredSize);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.ContentSizeFitter.FitMode o = (UnityEngine.UI.ContentSizeFitter.FitMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

