//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_Scrollbar_DirectionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.Scrollbar.Direction));
		L.RegVar("LeftToRight", get_LeftToRight, null);
		L.RegVar("RightToLeft", get_RightToLeft, null);
		L.RegVar("BottomToTop", get_BottomToTop, null);
		L.RegVar("TopToBottom", get_TopToBottom, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LeftToRight(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.Scrollbar.Direction.LeftToRight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_RightToLeft(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.Scrollbar.Direction.RightToLeft);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BottomToTop(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.Scrollbar.Direction.BottomToTop);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TopToBottom(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.Scrollbar.Direction.TopToBottom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.Scrollbar.Direction o = (UnityEngine.UI.Scrollbar.Direction)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

